
[sweeper_maid-common-config]
#If 0, disable item sweeping. If > 0, cool down (in seconds) between two item sweeping.
#Range: 0 ~ 360000
ITEM_SWEEP_INTERVAL = 30
#Other entities of types will be killed when cleaning, e.g. arrows. You can also kill mobs or even players by setting this.
EXTRA_ENTITY_TYPES = ["minecraft:arrow", "minecraft:spectral_arrow", "oceanworld:drip_ice"]
#What message will be sent to players when there's 15s, 30s and 60s left to sweep. "$1" stands for the remaining time (in seconds).
MESSAGE_BEFORE_SWEEP_15_30_60 = "[扫地女仆]：我将在 $1 秒后打扫地板！"
#What message will be sent to players when there's 1s~10s left to sweep. "$1" stands for the remaining time (in seconds).
MESSAGE_BEFORE_SWEEP_1_10 = "[扫地女仆]：我将在 $1 秒后打扫地板！"
#What message will be sent to players after a sweep. "$1" stands for the number of killed dropped items, and "$2" stands for the number of killed entities.
MESSAGE_AFTER_SWEEP = "[扫地女仆]：清扫过程中清理了 $1 个掉落物品和 $2 个不必要的实体。"
#What chat message will be sent to players after a sweep. Command will be appended to the end of the chat message.
CHAT_MESSAGE_AFTER_SWEEP = "[扫地女仆]：有遗漏的东西吗？让我们检查一下垃圾箱： "
#What message will be sent to players when open a wrong dustbin.
MESSAGE_WRONG_DUSTBIN = "[扫地女仆]：笨蛋!你找错地方了!"
#Permission level of a player to open the dustbin.
#Range: 0 ~ 4
PERMISSION_LEVEL_DUSTBIN = 0
#Items in this list will be cleaned but not added to the dustbin.
ITEM_BLACKLIST = ["minecraft:cobblestone", "minecraft:sand"]


